variables:
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  DOCKER_TLS_CERTDIR: "/certs"

  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

image: maven:3.6.3-openjdk-17

stages:
  - compile
  - test
  - build
  - deploy

cache:
  paths:
    - .m2/repository
    - target
  
deploy:
  image: mcr.microsoft.com/azure-cli:latest
  stage: deploy
  before_script:
    - export  IMAGE_TAG=$CI_COMMIT_SHORT_SHA
    - az login --username $AZURE_USER --password $AZURE_PASSWORD
  script: 
    - az aks install-cli
    - kubectl
    - az aks get-credentials -n wallet-wise-dev-test -g wallet-wise-dev-test --admin
    - sed -i 's/<IMAGE_TAG>/'$IMAGE_TAG'/g' deployment.yml
    - kubectl apply -f deployment.yml
  only:
    - staging