image: maven:3-jdk-11

stages:
  - build
  - test
  - analysis

build:
  stage: build
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

test:
  stage: test
  script:
    - mvn verify
    - cat target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/TEST-*.xml

analyze-source-code:
  stage: analysis
  script:
    - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
