services:
  # Eureka server
  discovery-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker